language: python
python:
- '3.6'
script:
- python --version
deploy:
  provider: s3
  access_key_id: AKIAJCTYCGW5JNLQCRSA
  secret_access_key:
    secure: km1frEylxPkGdnxSj7Cx8zQMVtVaRx8kaeC5JOmkp+KE38BzIR9f2+ZHT0VuVPb0/M40M2r727MemikBOcROHDKrC7Wl7vFYL0w68J8QQ30vKR+0Q1jgkNcBy9rTfnsQc1aKhYr1eTiSv5Xj0MiYoC+6WYHTL/d1gD+UN336tu/iGtocjyRr1FSHdb3wRf0gdgLuPZFK/NOcQ1MMLHrxIhc1nj6zSLBVRMhK3DWemBliDzypYNpCVsPTVIqGLzMzM8E0374rQ68rO8OyQy0GnnzW1vpEOR+cQ52IxEStJmQRzvH8+Cht2q3Qr3lxUBJddcmp1cWq0MoMNKZBzqWQejAjDP0+R2vBDMng+8UqAw2biFGWFHY3o578XrPJAbzacQAIeQYnsRRQ7AG4kE58LCoeFQTQts5ccZNXySgxIQhXywQ9Gr1LmxVbKMmu8frMzNud8+cDoO+MgbMZ6wshi9mIdsjmdAiLypAZ9SUT2RYngsPnjKz+3YNTxvId1SQKifbxAuadCI7KpTyuhRnWI8XlzLhjSICYP9BBiA9TxhbKWx6hRz6TtzVgvaubStk9/nj3IFuMcGdS7O7aVWOcE17mgtSHbqNIFpS7BVsWnteyud/19qbLNIKkoZeTXH4kS2qJI1o7OTLxRAmzXaeGao1G3BNzxTfZH12vkvEWCCc=
  bucket: osf-staging-static
